name: STAMP_v2xreal_Pyramid_stage1_m1_m2_base #_fix_softmax
root_dir: "/data/dataset/v2x-real/train"
validate_dir: "/data/dataset/v2x-real/test"
test_dir: "/data/dataset/v2x-real/test"

yaml_parser: "load_general_params"
train_params:
  batch_size: &batch_size 4
  epoches: 20
  eval_freq: 1
  save_freq: 1
  max_cav: 5

comm_range: 70
input_source: ['lidar']
label_type: 'lidar'
num_class: &num_class 3
cav_lidar_range: &cav_lidar [-102.4, -51.2, -15, 102.4, 51.2, 15]
dataset_mode: 'ic'

heter:
  assignment_path: "opencood/modality_assign/v2xreal_4modality.json" 
  ego_modality: &ego_modality "m0"
  mapping_dict:
    m1: m0
    m2: m0
    m3: none
    m4: none
  modality_setting:
    m0:
      sensor_type: &sensor_type_m0 'lidar'
      core_method: &core_method_m0 "point_pillar"

      # lidar requires preprocess
      preprocess:
        # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
        core_method: 'SpVoxelPreprocessor'
        args:
          voxel_size: &voxel_size [0.4, 0.4, 30]
          max_points_per_voxel: 32
          max_voxel_train: 32000
          max_voxel_test: 70000
        # lidar range for each individual cav.
        cav_lidar_range: *cav_lidar

fusion:
  core_method: 'intermediateheter3class'
  dataset: 'v2xreal'
  args: 
    proj_first: false
    grid_conf: None # place-holder
    data_aug_conf: None # place-holder


preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: [0.4, 0.4, 30] # useful
    max_points_per_voxel: 1 # useless
    max_voxel_train: 1 # useless
    max_voxel_test: 1 # useless
  # lidar range for each individual cav.
  cav_lidar_range: *cav_lidar
  num_class: *num_class
  anchor_generator_config: &anchor_generator_config
    - 'class_name': 'vehicle'
      'anchor_sizes': [ [ 3.9, 1.6, 1.56 ] ]
      'anchor_rotations': [ 0, 1.57 ]
      'anchor_bottom_heights': [ -1.78 ]
      'align_center': True
      'feature_map_stride': 4
      'matched_threshold': 0.6
      'unmatched_threshold': 0.45
    - 'class_name': 'pedestrian'
      'anchor_sizes': [ [ 0.8, 0.6, 1.73 ] ]
      'anchor_rotations': [ 0, 1.57 ]
      'anchor_bottom_heights': [ -0.6 ]
      'align_center': True
      'feature_map_stride': 4
      'matched_threshold': 0.5
      'unmatched_threshold': 0.35
    - 'class_name': 'truck'
      'anchor_sizes': [ [ 8, 3, 3 ] ]
      'anchor_rotations': [ 0, 1.57 ]
      'anchor_bottom_heights': [ -1.78 ]
      'align_center': True
      'feature_map_stride': 4
      'matched_threshold': 0.6
      'unmatched_threshold': 0.45


# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor3Heads' 
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 4
    num: &anchor_num 2
    anchor_generator_config: *anchor_generator_config
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl' # hwl or lwh
  max_num: 150 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

# model related
model:
  core_method: heter_pyramid_collab_mc_w_stamp
  args:
    stage: collab_train
    ego_modality: *ego_modality
    lidar_range: *cav_lidar
    num_class: *num_class
    fix_encoder: False

    m0:
      core_method: *core_method_m0
      sensor_type: *sensor_type_m0
      lidar_range: *cav_lidar
      num_class: *num_class

      encoder_args:
        voxel_size: *voxel_size
        lidar_range: *cav_lidar
        pillar_vfe:
          use_norm: true
          with_distance: false
          use_absolute_xyz: true
          num_filters: [64]
        point_pillar_scatter:
          num_features: 64

      backbone_args:
        layer_nums: [3, 5, 8]
        layer_strides: [2, 2, 2]
        num_filters: [64, 128, 256]
        upsample_strides: [1, 2, 4]
        num_upsample_filter: [128, 128, 128]

      shrink_header: 
        kernal_size: [ 3 ]
        stride: [ 2 ]
        padding: [ 1 ]
        dim: [ 256 ]
        input_dim: 384 # 128 * 3

      aligner_args:
        core_method: identity

      in_head: 384
      anchor_number: *anchor_num
      dir_args: *dir_args

      fusion_method: pyramid
      fusion_backbone:
        resnext: true
        stage: collab
        layer_nums: [3, 5, 8]
        layer_strides: [1, 2, 2]
        num_filters: [64, 128, 256]
        upsample_strides: [1, 2, 4]
        num_upsample_filter: [128, 128, 128]
        inplanes: 256

loss:
  core_method: point_pillar_pyramid_loss_mc
  args:
    num_class: *num_class
    pos_cls_weight: 2.0
    cls:
      type: 'SigmoidFocalLoss'
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: 'WeightedSmoothL1Loss'
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: 'WeightedSoftmaxClassificationLoss'
      weight: 0.2
      args: *dir_args
    depth:
      weight: 1.0
    pyramid:
      relative_downsample: [1, 2, 4]
      weight: [0.4, 0.2, 0.1]


optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [15, 25]


